#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { createInterface } from 'node:readline';

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = q => new Promise(r => rl.question(q, a => r(a)));

async function main() {
  console.log('\n=== Website Improvement Loop — Init ===\n');
  const answers = {};
  answers.baseUrl = await ask('BASE_URL (e.g. https://yoursite.com): ');
  answers.budget = await ask('Budget cap in USD for Phase E (default: unlimited): ') || 'unlimited';
  answers.project = await ask('Project name (default: default): ') || 'default';
  answers.login = await ask('Login required? ENV var name (or skip): ') || '';
  answers.targetUser = await ask('Target user (one sentence, or skip): ') || '';
  answers.goal = await ask('Primary business goal (signup/revenue/retention/?, or skip): ') || '';

  const envPath = resolve('.env');
  let env = existsSync(envPath) ? readFileSync(envPath, 'utf8') + '\n' : '';
  env += '# Website Improvement Loop — generated by init\n';
  env += 'BASE_URL=' + answers.baseUrl + '\n';
  env += 'BUDGET=' + answers.budget + '\n';
  env += 'BASELINE_PROJECT=' + answers.project + '\n';
  if (answers.login) env += answers.login + '=\n';
  writeFileSync(envPath, env);
  console.log('Created .env');

  const claudeDir = resolve('.claude');
  const settingsPath = join(claudeDir, 'settings.json');
  let settings = {};
  if (existsSync(settingsPath)) settings = JSON.parse(readFileSync(settingsPath, 'utf8'));
  settings['website-improvement-loop'] = answers;
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
  console.log('Saved to .claude/settings.json');

  console.log('\nDone. Run /web-improvement-loop:full to start.\n');
  rl.close();
}
main().catch(e => { console.error(e); rl.close(); process.exit(1); });
